#https
server:
  port: 8888


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.117.74.236:3306/varsity?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: demo1
    password: Demo123456.

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true





